# Generated by Django 3.2 on 2021-05-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(default=1619978451, max_length=30, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('marital_status', models.CharField(choices=[('single', 'single'), ('married', 'married'), ('divorced', 'divorced'), ('other', 'other')], max_length=10)),
                ('nationality', models.CharField(choices=[('indian', 'indian'), ('other', 'other')], max_length=10)),
                ('address', models.TextField()),
                ('zipcode', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=12)),
                ('designation', models.CharField(max_length=30)),
                ('experience', models.FloatField()),
                ('joining_dt', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
